server:
  port: 8021
  servlet:
    context-path: '/LLD/parkingLot'
security:
  ignored: /**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
info:
  application:
    name: Parking Lot Application
    description: An Application for Parking Lot
    author: Akash Singh
    version: '@project.version@'
spring:
  profiles:
    active: dev